### ISSUE TITLE
Problems with FMU binary with Spawn

### ISSUE THREAD

**Issue by GiuseppeR96** [henze-research-group/MODRLC#42]
Hi, I'd like to run a Spawn example from my own master Python code using pyFMI. 
I ask OpenModelica to extract an FMU from a Buildings Library model (e.g. `Buildings.ThermalZones.EnergyPlus.Examples.SingleFamilyHouse.AirHeating`), then I try to load the model on Python:
`model = load_fmu("AirHeating.fmu")`
such FMU will not work on Python, yielding this error message:
```
pyfmi.fmi.InvalidBinaryException:
 The FMU could not be loaded. Error loading the binary. Could not load 
the FMU binary:The specified module could not be found
```

I also tried with FMpy:

```
from fmpy import *
from fmpy.util import plot_result
fmu = 'AirHeating.fmu'
dump(fmu)
fmi_info(fmu)
result = simulate_fmu(fmu)
plot_result(result)
```

This code yields this error message:
`Exception: Failed to load shared library C:\ ...\AppData\Local\Temp\tmpmysxzg5z\binaries\win64\FMU_model.dll. Could not find module 'C:\Users\...\AppData\Local\Temp\tmpmysxzg5z\binaries\win64\FMU_model.dll' (or one of its dependencies). Try using the full path with constructor syntax.
`
I tried inspecting an FMU from the MODRLC-actb project that uses spawn:
`https://github.com/henze-research-group/MODRLC/tree/actb/testcases/spawnrefsmalloffice/models`
and I noticed that the modelDescription file includes explicit references to the spawn exe, namely:
```
<ScalarVariable name="mod.building.spawnExe" valueReference="805306368" description="Name of the spawn executable, without extension, such as spawn-0.2.0-d7f1e095f3" causality="local" variability="constant" initial="exact">
			<String start="spawn-0.2.0-d7f1e095f3" />
```
which are absent in the FMU that I extracted with OpenModelica. Besides, there are differences in the binaries and resouces folders between the forementioned example and my own, OpenModelica generated FMU.
May this be relevant?

It is worth noticing that:

- Spawn models work properly if run directly from OpenModelica
- FMUs extracted with OpenModelica that do not include Spawn can be run from python with both pyFMI and FMpy

 
Details on software and setup:
 • OS: Windows 10
 • OpenModelica v1.19.0-dev.beta1 (64-bit) and OpenModelica v1.20.0-dev-327-g42e1d1bbb6 (64-bit) (attempted with both version)
 • FMI version: 2.0
 • Python 3.8

**Comment by ThibaultMarzullo** [comment]
Ciao @GiuseppeR96 ,

While I cannot talk for the Spawn development team, I can tell you how we compile our models. If I cannot help you solve this issue, then I suggest you reach our to the Spawn team.

We do not compile the FMU directly from the Modelica IDE, instead we use Michael Wetter's Docker image with pyModelica installed to compile and export the FMU.
If you are familiar with Docker, I suggest you create a container based on `michaelwetter/ubuntu-1804_jmodelica_trunk`. If you want to see an example of a Dockerfile used for creating such a container, see [this file, found in the testing folder](https://github.com/henze-research-group/MODRLC/blob/actb/testing/Dockerfile).
Within the docker container, you can run a Python script with the following:
`from pymodelica import compile_fmu`
`fmu_path = compile_fmu(model_path, file_name)`
This should save a compiled FMU in the Docker container. There are simple functions for copying from/to docker containers, you can find this information online pretty easily. So in summary, you would need to:
- create a python script with at minimum the two lines above
- create a Docker container based on `michaelwetter/ubuntu-1804_jmodelica_trunk`
- run the container and copy 1) your .mo model and 2) your python script to the Docker container
- run the python script within the container
- copy the output of the script, the .fmu, from the container to your system

Having Docker in the way seems cumbersome, but it is quite easy to be honest. The reason we use this Docker container is because it is one of the last available sources for JModelica, and Spawn usually compiles well with JModelica.

In our case, since we need some extra steps during compilation, we are doing things a little differently. I write it here in case you find something useful for your application:
- we include a compile_fmu.py file in our test case
- we include the appropriate resources, as required by BOPTEST, in companion folders
- the compile_fmu.py code is executed on the Docker container I mentioned above, and it calls a function found in `parsing/parser.py`
- the function in `parsing/parser.py` calls, in turn, the compile_fmu function from pyModelica that I described in the code snippet above. This is the only thing you would need in your particular application.
- the same function then packages the FMU following the BOPTEST requirements, which ask that some resources and some parameter files should be included in the FMU. Unless you want to run the FMU in BOPTEST or the ACTB, you do not need this at all.

Last note: we were using the Modelica Buildings Library v8.0.0 to build our Spawn models, but now v9.0.0 is out. You should consider updating if you have a chance. Spawn is being actively developed, and I believe it now runs on Windows systems too.

Let me know if you have other questions on compiling Spawn FMUs, or on setting the Docker image up.
Cordiali saluti
Thibault

**Comment by ThibaultMarzullo** [comment]
I will reopen this issue if there is activity on this thread
